### ISSUE TITLE
throws error when 'canihaz' key is not present

### ISSUE THREAD

**Issue by jcw** [3rd-Eden/canihaz#11]
on line canihaz/index.js:193

When using canihaz to load modules not in package.json, it shouldn't really complain if there are no dependencies in the package.json file, IMO.

The error could be avoided with `dependencies = dependencies || {};` on line 102, for example. Not sure that's the best fix.

**Comment by indexzero** [comment]
@3rd-Eden I am also seeing this with the following:

```
$ node
> var canihaz = require('canihaz');
undefined
> canihaz()
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at canihazitplxktnxilubai (canihaz/index.js:192:10)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
    at REPLServer.Interface._line (readline.js:553:8)
```
